// Mirrors RandevumKolay.Domain.Enums.BusinessCategory — serialized as camelCase
// strings (JsonStringEnumConverter(CamelCase) in Program.cs), not numbers.
export const businessCategoryLabels: Record<string, string> = {
  beautySalon: 'Güzellik Salonu',
  barbershop: 'Berber',
  clinic: 'Klinik',
  dentist: 'Diş Hekimi',
  physiotherapy: 'Fizyoterapi',
  gym: 'Spor Salonu',
  personalTrainer: 'Kişisel Antrenör',
  yoga: 'Yoga',
  spa: 'Spa',
  nailSalon: 'Nail Salon',
  tattoo: 'Dövme',
  veterinarian: 'Veteriner',
  carService: 'Oto Servis',
  carWash: 'Oto Yıkama',
  repairService: 'Tamir Servisi',
  consultant: 'Danışman',
  psychologist: 'Psikolog',
  nutritionist: 'Diyetisyen',
  tutor: 'Özel Ders',
  photographer: 'Fotoğrafçı',
  other: 'Diğer',
}
