// Mirrors RandevumKolay.Domain.Enums.BusinessCategory
export const businessCategoryLabels: Record<number, string> = {
  1: 'Güzellik Salonu',
  2: 'Berber',
  3: 'Klinik',
  4: 'Diş Hekimi',
  5: 'Fizyoterapi',
  6: 'Spor Salonu',
  7: 'Kişisel Antrenör',
  8: 'Yoga',
  9: 'Spa',
  10: 'Nail Salon',
  11: 'Dövme',
  12: 'Veteriner',
  13: 'Oto Servis',
  14: 'Oto Yıkama',
  15: 'Tamir Servisi',
  16: 'Danışman',
  17: 'Psikolog',
  18: 'Diyetisyen',
  19: 'Özel Ders',
  20: 'Fotoğrafçı',
  99: 'Diğer',
}
