import type { Module } from '@/types'

export const defaultModules: Module[] = [
  {
    id: 'appointments',
    name: 'Randevu Sistemi',
    description: 'Online randevu alma, yönetme ve takip sistemi',
    icon: 'CalendarCheck',
    category: 'core',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'calendar',
    name: 'Takvim',
    description: 'Görsel takvim ve program yönetimi',
    icon: 'CalendarDays',
    category: 'core',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'services',
    name: 'Hizmet Yönetimi',
    description: 'Sunduğunuz hizmetleri, süreleri ve fiyatları yönetin',
    icon: 'Scissors',
    category: 'core',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'employees',
    name: 'Personel Yönetimi',
    description: 'Çalışanlarınızı, çalışma saatlerini ve takvimlerini yönetin',
    icon: 'UserCheck',
    category: 'core',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'customers',
    name: 'Müşteri Yönetimi',
    description: 'Müşteri profilleri, geçmiş ve notlar',
    icon: 'Users',
    category: 'core',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'packages',
    name: 'Paket Sistemi',
    description: 'Hizmet paketleri ve çoklu seans yönetimi',
    icon: 'Package',
    category: 'core',
    isEnabled: true,
    isBuiltIn: false,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'payments',
    name: 'Ödeme ve Finans',
    description: 'Tahsilatlar, faturalar ve finansal raporlar',
    icon: 'CreditCard',
    category: 'finance',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'reports',
    name: 'Raporlar ve Analitik',
    description: 'Detaylı iş performans raporları ve analizler',
    icon: 'BarChart3',
    category: 'advanced',
    isEnabled: true,
    isBuiltIn: true,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'campaigns',
    name: 'Kampanya Sistemi',
    description: 'Özel kampanyalar ve promosyon yönetimi',
    icon: 'Tag',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'gift-coupons',
    name: 'Hediye Kupon',
    description: 'Hediye kupon oluşturma ve yönetimi',
    icon: 'Gift',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'discounts',
    name: 'İndirim Sistemi',
    description: 'Müşteri indirimleri ve özel fiyatlandırma',
    icon: 'Percent',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'reviews',
    name: 'Değerlendirmeler',
    description: 'Müşteri yorum ve puanlama yönetimi',
    icon: 'Star',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'online-booking',
    name: 'Online Rezervasyon',
    description: 'Müşterilerin online randevu alabilmesi için rezervasyon sayfası',
    icon: 'Globe',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'website-builder',
    name: 'Site Oluşturucu',
    description: 'Kendi işletme sitenizi oluşturun ve özelleştirin',
    icon: 'Layout',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'sms-marketing',
    name: 'SMS Pazarlama',
    description: 'Müşterilere SMS kampanyaları ve hatırlatıcılar gönderin',
    icon: 'MessageSquare',
    category: 'communication',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'email-marketing',
    name: 'E-posta Pazarlama',
    description: 'E-posta kampanyaları ve otomatik bildirimler',
    icon: 'Mail',
    category: 'communication',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'analytics-advanced',
    name: 'Gelişmiş Analitik',
    description: 'AI destekli tahminler ve gelişmiş iş zekası raporları',
    icon: 'TrendingUp',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'maps',
    name: 'Haritalar',
    description: 'İşletme konumunuzu harita üzerinde gösterin, yol tarifi ve konum yönetimi',
    icon: 'MapPin',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'whatsapp-bot',
    name: 'WhatsApp Bot',
    description: 'WhatsApp üzerinden otomatik randevu alma ve müşteri iletişimi',
    icon: 'WhatsApp',
    category: 'communication',
    isEnabled: true,
    isBuiltIn: false,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'chatbot',
    name: 'Canlı Chatbot',
    description: 'Web sitenizde müşterilere otomatik cevap veren yapay zeka chatbot',
    icon: 'MessageSquare',
    category: 'communication',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'custom',
    version: '1.0.0',
  },
  {
    id: 'forms',
    name: 'Form Yönetimi',
    description: 'Başvuru, iletişim ve özel formlar oluşturun ve yönetin',
    icon: 'FileText',
    category: 'core',
    isEnabled: true,
    isBuiltIn: false,
    isPremium: false,
    version: '1.0.0',
  },
  {
    id: 'walkin-queue',
    name: 'Sıra / Walk-in Yönetimi',
    description: 'Randevusuz gelen müşterileri sıraya alın, bekleme sürelerini takip edin',
    icon: 'ListOrdered',
    category: 'core',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'custom',
    version: '1.0.0',
  },
  {
    id: 'loyalty',
    name: 'Sadakat Programı',
    description: 'Puan ve ödül sistemi ile müşteri bağlılığını artırın',
    icon: 'Award',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'waiting-list',
    name: 'Bekleme Listesi',
    description: 'Dolu slotlar için bekleme listesi oluşturun, açılan randevuları otomatik teklif edin',
    icon: 'ClipboardList',
    category: 'core',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'social-media',
    name: 'Sosyal Medya',
    description: 'Instagram, Facebook ve Google rezervasyon butonlarını yönetin, paylaşım yapın',
    icon: 'Share2',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'surveys',
    name: 'Anket & Feedback',
    description: 'Randevu sonrası otomatik memnuniyet anketi gönderin, sonuçları analiz edin',
    icon: 'ClipboardCheck',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'products',
    name: 'Ürün & Stok Yönetimi',
    description: 'Ürün kataloğu, stok takibi ve düşük stok uyarıları',
    icon: 'Package',
    category: 'finance',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'receivables',
    name: 'Cari Alacak & Taksit',
    description: 'Müşteri alacakları ve taksitli ödeme takibi',
    icon: 'CreditCard',
    category: 'finance',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'performance',
    name: 'Personel Performans',
    description: 'Personel bazlı randevu ve gelir performans analizi',
    icon: 'TrendingUp',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'commissions',
    name: 'Prim & Hak Ediş',
    description: 'Personel komisyon, prim ve hak ediş hesaplama',
    icon: 'Award',
    category: 'finance',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'debts',
    name: 'Borç & Ödeme Takibi',
    description: 'İşletme borçları, ödemeler ve vade takibi',
    icon: 'AlertCircle',
    category: 'finance',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'branches',
    name: 'Çoklu Şube Yönetimi',
    description: 'Birden fazla şubeyi tek panelden yönetin',
    icon: 'Building2',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'advertisements',
    name: 'Reklam Yönetimi',
    description: 'Reklam oluşturun, paket seçin ve performansı takip edin',
    icon: 'Megaphone',
    category: 'marketing',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'business',
    version: '1.0.0',
  },
  {
    id: 'recommendations',
    name: 'AI Öneri Motoru',
    description: 'Yapay zeka destekli hizmet ve ürün önerileri, zamanı gelmiş hatırlatmalar',
    icon: 'Sparkles',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'no-show-prediction',
    name: 'No-Show Tahmin & Kapora',
    description: 'Randevuya gelmeme riskini tahmin edin, otomatik kapora sistemi',
    icon: 'ShieldAlert',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'deposits',
    name: 'Kapora Yönetimi',
    description: 'Kapora/Depozito takibi, iade ve mahsup işlemleri',
    icon: 'Banknote',
    category: 'finance',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
  {
    id: 'smart-schedule',
    name: 'Akıllı Vardiya Planlama',
    description: 'AI destekli vardiya optimizasyonu, talep tahmini ve overbooking önerileri',
    icon: 'Brain',
    category: 'advanced',
    isEnabled: false,
    isBuiltIn: false,
    isPremium: true,
    requiredPlan: 'professional',
    version: '1.0.0',
  },
]
