import type { NavGroup } from '@/types'

export const navigationConfig: NavGroup[] = [
  {
    id: 'core',
    label: 'Genel',
    isCollapsible: false,
    items: [
      { id: 'dashboard', label: 'Gösterge Paneli', to: '/dashboard', icon: 'LayoutDashboard' },
      { id: 'calendar', label: 'Takvim', to: '/calendar', icon: 'CalendarDays' },
      { id: 'appointments', label: 'Randevular', to: '/appointments', icon: 'CalendarCheck', moduleId: 'appointments' },
    ],
  },
  {
    id: 'management',
    label: 'Yönetim',
    icon: 'Briefcase',
    isCollapsible: true,
    defaultOpen: true,
    items: [
      { id: 'services', label: 'Hizmetler', to: '/services', icon: 'Scissors', moduleId: 'services' },
      { id: 'packages', label: 'Paketler', to: '/packages', icon: 'Package', moduleId: 'packages' },
      { id: 'employees', label: 'Çalışanlar', to: '/employees', icon: 'UserCheck', moduleId: 'employees' },
      { id: 'customers', label: 'Müşteriler', to: '/customers', icon: 'Users', moduleId: 'customers' },
    ],
  },
  {
    id: 'finance',
    label: 'Finans & Pazarlama',
    icon: 'TrendingUp',
    isCollapsible: true,
    defaultOpen: false,
    items: [
      { id: 'payments', label: 'Ödemeler', to: '/payments', icon: 'CreditCard', moduleId: 'payments' },
      { id: 'campaigns', label: 'Kampanyalar', to: '/campaigns', icon: 'Tag', moduleId: 'campaigns' },
      { id: 'gift-coupons', label: 'Hediye Kuponlar', to: '/gift-coupons', icon: 'Gift', moduleId: 'gift-coupons' },
      { id: 'discounts', label: 'İndirimler', to: '/discounts', icon: 'Percent', moduleId: 'discounts' },
      { id: 'products', label: 'Ürün & Stok', to: '/products', icon: 'Package', moduleId: 'products' },
      { id: 'receivables', label: 'Cari Alacaklar', to: '/receivables', icon: 'CreditCard', moduleId: 'receivables' },
      { id: 'commissions', label: 'Prim & Hak Ediş', to: '/commissions', icon: 'Award', moduleId: 'commissions' },
      { id: 'debts', label: 'Borç Takibi', to: '/debts', icon: 'AlertCircle', moduleId: 'debts' },
      { id: 'advertisements', label: 'Reklam Yönetimi', to: '/advertisements', icon: 'Megaphone', moduleId: 'advertisements' },
      { id: 'deposits', label: 'Kapora Yönetimi', to: '/deposits', icon: 'Banknote', moduleId: 'deposits' },
    ],
  },
  {
    id: 'customer-tools',
    label: 'Müşteri Araçları',
    icon: 'Heart',
    isCollapsible: true,
    defaultOpen: false,
    items: [
      { id: 'reports', label: 'Raporlar', to: '/reports', icon: 'BarChart3', moduleId: 'reports' },
      { id: 'performance', label: 'Personel Performans', to: '/performance', icon: 'TrendingUp', moduleId: 'performance' },
      { id: 'loyalty', label: 'Sadakat Programı', to: '/loyalty', icon: 'Award', moduleId: 'loyalty' },
      { id: 'waiting-list', label: 'Bekleme Listesi', to: '/waiting-list', icon: 'ClipboardList', moduleId: 'waiting-list' },
      { id: 'walkin-queue', label: 'Sıra Yönetimi', to: '/walkin-queue', icon: 'ListOrdered', moduleId: 'walkin-queue' },
      { id: 'surveys', label: 'Anket & Feedback', to: '/surveys', icon: 'ClipboardCheck', moduleId: 'surveys' },
      { id: 'recommendations', label: 'AI Öneriler', to: '/recommendations', icon: 'Sparkles', moduleId: 'recommendations' },
      { id: 'no-show-prediction', label: 'No-Show Tahmin', to: '/no-show-prediction', icon: 'ShieldAlert', moduleId: 'no-show-prediction' },
    ],
  },
  {
    id: 'communication',
    label: 'İletişim & Sosyal',
    icon: 'Share2',
    isCollapsible: true,
    defaultOpen: false,
    items: [
      { id: 'social-media', label: 'Sosyal Medya', to: '/social-media', icon: 'Share2', moduleId: 'social-media' },
      { id: 'whatsapp-bot', label: 'WhatsApp Bot', to: '/whatsapp-bot', icon: 'WhatsApp', moduleId: 'whatsapp-bot' },
      { id: 'chatbot', label: 'Canlı Chatbot', to: '/chatbot', icon: 'MessageSquare', moduleId: 'chatbot' },
      { id: 'forms', label: 'Formlar', to: '/forms', icon: 'FileText', moduleId: 'forms' },
      { id: 'maps', label: 'Haritalar', to: '/maps', icon: 'MapPin', moduleId: 'maps' },
    ],
  },
  {
    id: 'system',
    label: 'Sistem',
    icon: 'Settings',
    isCollapsible: true,
    defaultOpen: false,
    items: [
      { id: 'notifications', label: 'Bildirimler', to: '/notifications', icon: 'Bell' },
      { id: 'smart-schedule', label: 'Akıllı Vardiya', to: '/smart-schedule', icon: 'Brain', moduleId: 'smart-schedule' },
      { id: 'branches', label: 'Şube Yönetimi', to: '/branches', icon: 'Building2', moduleId: 'branches' },
      { id: 'subscription', label: 'Abonelik', to: '/subscription', icon: 'CreditCard' },
      { id: 'plugins', label: 'Eklentiler', to: '/plugins', icon: 'Puzzle' },
      { id: 'support', label: 'Destek', to: '/support', icon: 'LifeBuoy' },
      { id: 'settings', label: 'Ayarlar', to: '/settings', icon: 'Settings' },
    ],
  },
]
