import type { ExpoConfig, ConfigContext } from 'expo/config';

/**
 * Environment-aware Expo config.
 *
 * API base URL resolution order:
 *   1. EXPO_PUBLIC_API_URL (set in .env or the shell / EAS build env)
 *   2. the built-in default for the current profile
 *
 * Set APP_ENV=development (or run `npm run dev`) to point the app at a local API.
 */
const APP_ENV = (process.env.APP_ENV ?? 'production') as 'development' | 'staging' | 'production';

const API_URLS: Record<typeof APP_ENV, string> = {
  development: 'http://localhost:5280/api/v1',
  staging: 'https://api-randevumkolay.azurewebsites.net/api/v1',
  production: 'https://api-randevumkolay.azurewebsites.net/api/v1',
};

const apiUrl = process.env.EXPO_PUBLIC_API_URL ?? API_URLS[APP_ENV];

/**
 * Single source for the app version.
 *
 * Native projects are generated by prebuild (CNG) rather than committed, so
 * `runtimeVersion` can follow the appVersion policy below and stay in sync
 * automatically. Existing installs only receive OTA updates built against the
 * same runtime version, so bumping this cuts older builds off from updates.
 */
const APP_VERSION = '1.0.0';

// `androidNavigationBar` is a valid Expo key but is missing from ExpoConfig in
// this SDK's types, so the literal is asserted rather than widened.
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'JetRandevu',
  slug: 'jetrandevu',
  version: APP_VERSION,
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'jetrandevu',
  userInterfaceStyle: 'automatic',
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.jetrandevu.app',
    buildNumber: '1',
    infoPlist: {
      // Required by Apple when the app talks to a server; ours is HTTPS-only.
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/images/adaptive-icon.png',
      backgroundColor: '#8A4A3F',
    },
    package: 'com.jetrandevu.app',
    versionCode: 1,
  },
  androidNavigationBar: {
    visible: 'immersive',
  },
  web: {
    bundler: 'metro',
    output: 'single',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    'expo-font',
    'expo-secure-store',
    'expo-image',
    'expo-splash-screen',
    'expo-web-browser',
    '@react-native-community/datetimepicker',
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'JetRandevu, yakınındaki işletmeleri mesafeye göre listelemek için konumunu kullanır.',
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission: 'JetRandevu, profil fotoğrafını değiştirebilmen için galerine erişir.',
      },
    ],
    [
      'expo-notifications',
      {
        icon: './assets/images/icon.png',
        color: '#C97D72',
      },
    ],
  ],
  // OTA updates: ship JS-only fixes without another store review.
  // `runtimeVersion` is tied to the native ABI, so a build only accepts
  // updates compiled against the same native code.
  updates: {
    url: 'https://u.expo.dev/a85921df-08a8-4f7a-aceb-b806e3a100b8',
    fallbackToCacheTimeout: 0,
    checkAutomatically: 'NEVER',
  },
  runtimeVersion: {
    policy: 'appVersion',
  },
  experiments: {
    typedRoutes: true,
  },
  owner: 'dogancanaras49',
  extra: {
    apiUrl,
    appEnv: APP_ENV,
    // Set by `eas init`. Also read at runtime by pushNotifications.ts when
    // requesting the Expo push token.
    eas: {
      projectId: 'a85921df-08a8-4f7a-aceb-b806e3a100b8',
    },
  },
} as ExpoConfig);
